apiVersion: nkp.io/v1alpha1
kind: Devspace
metadata:
  name: devspace1
spec:
  crossplane:
    compositionRef:
      name: devspace
  id: torg-space
  nkpVersion: v2.17.1
  pc:
    key: 'nx2Tech294!'
