apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: realms.nkp.io
spec:
  scope: Cluster
  group: nkp.io
  names:
    kind: Realm
    plural: realms
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                id:
                  type: string
                nkpVersion:
                  type: string
                pc:
                  type: object
                  properties:
                    key:
                      type: string
                    ipAddress:
                      type: string
                    clusterName:
                      type: string
                    subnetName:
                      type: string
                  required:
                    - key
                    - ipAddress
                    - clusterName
                    - subnetName
                k8sImageName:
                  type: string
                k8sVersion:
                  type: string
                loadBalancer:
                  type: object
                  properties:
                    vip:
                      type: string
                    start:
                      type: string
                    end:
                      type: string
                  required:
                    - start
                    - end
                    - vip
                #apps:
                  #type: array
                  #items:
                    #type: string
              required:
                - id
                - pc
                - k8sImageName
                - k8sVersion
                - loadBalancer
            status:
              properties:
                workspaceNamespace:
                  type: string
              type: object
