apiVersion: nkp.io/v1alpha1
kind: WorkloadCluster
metadata:
  name: devtest1
spec:
  crossplane:
    compositionRef:
      name: devtest
  workloadClusterName: devtest-1 # Change name if you want
  workSpaceName: devtest1
  nkpVersion: v2.17.1 # update when needed
  pc:
    key: 'nx2Tech743!' # MODIFY_THIS
    ipAddress: 10.38.35.7 # MODIFY_THIS
    clusterName: PHX-POC263 # MODIFY_THIS
    subnetName: secondary-PHX-POC263 # MODIFY_THIS
  loadBalancer:
    start: 10.38.35.146 # MODIFY_THIS
    end: 10.38.35.155 # MODIFY_THIS
    vip: 10.38.35.145 # MODIFY_THIS
  k8sImageName: nkp-ubuntu-24.04-release-cis-1.34.3-20260504025514.qcow2 # Use diff image if needed
  k8sVersion: v1.34.3 # Update k8s when needed
