apiVersion: nkp.io/v1alpha1
kind: ClusterProfile
metadata:
  name: production
  labels:
    refresh: "1"
spec:
  crossplane:
    compositionRef:
      name: production
  workSpaceName: production
  workloadClusterName: production-1
  nkpVersion: v2.17.1
  pc:
    key: 'nx2Tech989!' # MODIFY_THIS
    ipAddress: 10.38.35.7 # MODIFY_THIS
    clusterName: PHX-POC263 # MODIFY_THIS
    subnetName: primary-PHX-POC263 # MODIFY_THIS
  loadBalancer:
    start: 10.38.35.122 # MODIFY_THIS
    end: 10.38.35.125 # MODIFY_THIS
    vip: 10.38.35.121 # MODIFY_THIS
  k8sImageName: nkp-ubuntu-24.04-release-cis-1.34.3-20260226170017 # Use diff image if needed
  k8sVersion: v1.34.3 # Update k8s when needed
