apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"source.toolkit.fluxcd.io/v1beta1","kind":"GitRepository","metadata":{"annotations":{},"labels":{"kommander.d2iq.io/gitapps-gitrepository-type":"catalog","kommander.d2iq.io/gitrepository-type":"catalog"},"name":"ndb-operator-repo","namespace":"nkp-flux-provisioned-phvwv-jjxpb"},"spec":{"interval":"1m0s","ref":{"branch":"main"},"timeout":"20s","url":"https://github.com/jm-pedersen/ndb-operator-nkp-catalog.git"}}
  creationTimestamp: "2025-07-03T20:29:36Z"
  finalizers:
  - finalizers.fluxcd.io
  - kommander.d2iq.io/gitrepository-apps
  - kommander.d2iq.io/kommander-catalog-repository
  generation: 4
  labels:
    kommander.d2iq.io/gitapps-gitrepository-type: catalog
    kommander.d2iq.io/gitrepository-type: catalog
  name: ndb-operator-repo
  namespace: nkp-flux-provisioned-phvwv-jjxpb
  resourceVersion: "1917031341"
  uid: 9a568eb2-adb7-49c7-9edc-25bc708640f9
spec:
  interval: 1m0s
  ref:
    branch: main
  timeout: 20s
  url: https://github.com/jm-pedersen/ndb-operator-nkp-catalog.git
status:
  artifact:
    digest: sha256:2eb8020f266874dd62a3ccf80079bf996afba4036d2da91a8e177b6e090929ea
    lastUpdateTime: "2026-03-31T13:59:35Z"
    path: gitrepository/nkp-flux-provisioned-phvwv-jjxpb/ndb-operator-repo/a719d0e1dd7c1d99495d82c9b6a90438014de0ad.tar.gz
    revision: main@sha1:a719d0e1dd7c1d99495d82c9b6a90438014de0ad
    size: 1870
    url: http://source-controller.kommander-flux.svc.cluster.local./gitrepository/nkp-flux-provisioned-phvwv-jjxpb/ndb-operator-repo/a719d0e1dd7c1d99495d82c9b6a90438014de0ad.tar.gz
  conditions:
  - lastTransitionTime: "2026-04-23T16:31:28Z"
    message: stored artifact for revision 'main@sha1:a719d0e1dd7c1d99495d82c9b6a90438014de0ad'
    observedGeneration: 4
    reason: Succeeded
    status: "True"
    type: Ready
  - lastTransitionTime: "2026-03-31T13:59:35Z"
    message: stored artifact for revision 'main@sha1:a719d0e1dd7c1d99495d82c9b6a90438014de0ad'
    observedGeneration: 4
    reason: Succeeded
    status: "True"
    type: ArtifactInStorage
  observedGeneration: 4
