apiVersion: v1
data:
  credentials: WwogICAgewogICAgICAgICJ0eXBlIjogImJhc2ljX2F1dGgiLAogICAgICAgICJkYXRhIjogewogICAgICAgICAgICAicHJpc21DZW50cmFsIjogewogICAgICAgICAgICAgICAgInVzZXJuYW1lIjogImFkbWluIiwKICAgICAgICAgICAgICAgICJwYXNzd29yZCI6ICJueDJUZWNoNzQyISIKICAgICAgICAgICAgfQogICAgICAgIH0KICAgIH0KXQ==
kind: Secret
metadata:
  labels:
    cluster.x-k8s.io/provider: nutanix
    konvoy.d2iq.io/cluster-name: messaging1
    konvoy.d2iq.io/provider: nutanix
  name: messaging1-pc-credentials
  namespace: messaging-22npk-49jmp
type: Opaque
