apiVersion: workspaces.kommander.mesosphere.io/v1alpha1
kind: Workspace
metadata:
  annotations:
    kommander.mesosphere.io/description: ""
    kommander.mesosphere.io/display-name: messaging
    workspace.kommander.mesosphere.io/default-app-deployments-created: "true"
  creationTimestamp: "2026-04-13T13:57:30Z"
  finalizers:
  - kommander.mesosphere.io/workspacekustomization
  - workspaces.kommander.mesosphere.io/workspace
  generateName: messaging-
  generation: 2
  labels:
    caren.nutanix.com/namespace-sync: ""
    workspaces.kommander.mesosphere.io/workspace-name: messaging-22npk
  name: messaging-22npk
  resourceVersion: "40700"
  uid: dec56b02-dee7-4701-9692-214bb9a162e7
spec:
  clusterLabels:
    workspaces.kommander.mesosphere.io/workspace-ref: 10000e18-76d0-4e7b-ba2e-b5283b93fb56
  namespaceName: messaging-22npk-49jmp
  version: v2.17.1
status:
  conditions:
  - lastTransitionTime: "2026-04-13T13:57:30Z"
    status: "False"
    type: WorkspaceNamespaceConflict
  namespaceRef:
    name: messaging-22npk-49jmp
  version: v2.17.1
