apiVersion: workspaces.kommander.mesosphere.io/v1alpha1
kind: Workspace
metadata:
  annotations:
    kommander.mesosphere.io/description: ""
    kommander.mesosphere.io/display-name: yamltest
    workspace.kommander.mesosphere.io/default-app-deployments-created: "true"
  labels:
    caren.nutanix.com/namespace-sync: ""
    workspaces.kommander.mesosphere.io/workspace-name: yamltest-2026n
  name: yamltest-2026n
spec:
  namespaceName: yamltest-2026n-1
  version: v2.17.1
