apiVersion: nkp.io/v1alpha1
kind: ClusterProfile
metadata:
  name: devtest2
spec:
  crossplane:
    compositionRef:
      name: devtest
  workloadClusterName: devtest-2
  workSpaceName: devtest
  nkpVersion: v2.17.1
  pc:
    key: 'nx2Tech294!' # MODIFY_THIS
    ipAddress: 10.8.50.7 # MODIFY_THIS
    clusterName: RNO-SPOC007-3 # MODIFY_THIS
    subnetName: primary-RNO-SPOC007-3 # MODIFY_THIS
  loadBalancer:
    start: 10.8.50.117 # MODIFY_THIS
    end: 10.8.50.119 # MODIFY_THIS
    vip: 10.8.50.116 # MODIFY_THIS
  k8sImageName: nkp-ubuntu-24.04-release-cis-1.34.3-20260226170017
  k8sVersion: v1.34.3
