apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  volumes:
  - name: kube-api-access-rmcvz
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
    resources: {}
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-04-13T17:02:49Z"
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-rmcvz
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 10.38.34.44
  hostIPs:
  - ip: 10.38.34.44
  observedGeneration: 1
  phase: Running
  podIP: 192.168.1.1
  podIPs:
  - ip: 192.168.1.1
  qosClass: BestEffort
  startTime: "2026-04-13T17:02:40Z"
