---
apiVersion: v1
data:
  key: MTAuMzguMzQuNzo5NDQwOmFkbWluOm54MlRlY2g3NDIh
kind: Secret
metadata:
  labels:
    cluster.x-k8s.io/provider: nutanix
    konvoy.d2iq.io/cluster-name: messaging1
    konvoy.d2iq.io/provider: nutanix
  name: messaging1-pc-credentials-for-csi
  namespace: messaging-22npk-49jmp
type: Opaque
